<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PAudit</name>
   <tag></tag>
   <elementGuidId>9d422ad5-ebad-41f5-80e0-173783ac91bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/a[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f1c6b1ae-7451-489e-bb97-8795c5a5df86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-outlined MuiButton-outlinedSecondary MuiButton-sizeMedium MuiButton-outlinedSizeMedium MuiButton-root MuiButton-outlined MuiButton-outlinedSecondary MuiButton-sizeMedium MuiButton-outlinedSizeMedium css-1clrzpb</value>
      <webElementGuid>52a82f4d-4d07-4b00-98bf-3a4c1210ea35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f069d0d-2d77-41c5-9fa5-5998330e3194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/paudit/homepage</value>
      <webElementGuid>004a0416-e978-4133-90a7-9e1ee0c23de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAudit</value>
      <webElementGuid>b4d2229a-0681-4606-abc1-ba488e2aaf16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[1]/div[2]/div[1]/div[1]/div[@class=&quot;MuiBox-root css-1a13iho&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthMd MuiContainer-disableGutters css-1x1fie8&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthMd MuiContainer-disableGutters css-1x1fie8&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-outlined MuiPaper-rounded css-qdbqzv&quot;]/div[@class=&quot;MuiBox-root css-8oeqi8&quot;]/div[@class=&quot;MuiBox-root css-1bew4ia&quot;]/a[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-outlined MuiButton-outlinedSecondary MuiButton-sizeMedium MuiButton-outlinedSizeMedium MuiButton-root MuiButton-outlined MuiButton-outlinedSecondary MuiButton-sizeMedium MuiButton-outlinedSizeMedium css-1clrzpb&quot;]</value>
      <webElementGuid>6e5b01a5-76d4-42dd-8c02-98500a7d7a59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/a[14]</value>
      <webElementGuid>27d94b73-2698-401a-bfa2-c4ebf7b9f077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PAudit')]</value>
      <webElementGuid>dcf0df89-13b0-41e0-82b2-cbb9d4668e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owners manuals'])[1]/following::a[1]</value>
      <webElementGuid>4536152f-946e-4289-a855-bf35d5dfa3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NewDemo'])[1]/following::a[2]</value>
      <webElementGuid>9448ad23-88a7-4575-b869-ccdf60cbcaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PCI'])[1]/preceding::a[1]</value>
      <webElementGuid>b47dc190-c970-4313-b696-5abf0faebd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PVP'])[1]/preceding::a[2]</value>
      <webElementGuid>2f9dfba1-1806-4a8e-b343-848de2446c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAudit']/parent::*</value>
      <webElementGuid>7fa82b9d-7f85-4694-8bca-4095f5c35eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/paudit/homepage')]</value>
      <webElementGuid>f8440685-a41e-41a6-8e77-ae04728f210b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[14]</value>
      <webElementGuid>c372b76a-3dcc-47d7-88a5-9345c09bc0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/paudit/homepage' and (text() = 'PAudit' or . = 'PAudit')]</value>
      <webElementGuid>1da7f1e4-2cc9-46af-a431-0163c1b01c15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
