<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(testDe)_sa-i notranslate MuiIcon-root_757d4f</name>
   <tag></tag>
   <elementGuidId>037f5439-805b-459d-8137-f5c1841cc3cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paudit']/div/div/div[3]/div/div/div/div/div/table/tbody/tr/td[3]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sa-i.notranslate.MuiIcon-root.MuiIcon-fontSizeSmall.preview.css-1e0xsb8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>71562245-3048-4ec1-adaf-a8b3daccced6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sa-i notranslate MuiIcon-root MuiIcon-fontSizeSmall preview css-1e0xsb8</value>
      <webElementGuid>adc5f5de-614d-467c-86b3-5ab2763c67f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32d83800-4750-4e97-b110-94b0f54b2885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paudit&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[@class=&quot;MuiContainer-root undefined undefined css-runt2f&quot;]/div[3]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;jss12&quot;]/div[1]/div[1]/div[1]/table[@class=&quot;MuiTable-root css-1tww9e9&quot;]/tbody[@class=&quot;MuiTableBody-root css-1xnox0e&quot;]/tr[@class=&quot;MuiTableRow-root css-vb1k26&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body MuiTableCell-alignLeft MuiTableCell-sizeMedium css-1ja556r&quot;]/div[@class=&quot;btnsOnRight&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-colorSecondary MuiIconButton-sizeMedium css-m6yve9&quot;]/span[@class=&quot;sa-i notranslate MuiIcon-root MuiIcon-fontSizeSmall preview css-1e0xsb8&quot;]</value>
      <webElementGuid>e1c640e8-913f-46b4-aed1-32d6bf1c9f09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paudit']/div/div/div[3]/div/div/div/div/div/table/tbody/tr/td[3]/div/button/span</value>
      <webElementGuid>41010e8b-a92a-46fe-aa97-9ce2f9184e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/button/span</value>
      <webElementGuid>e8e91021-78c9-45a8-89a0-e516a06110c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
