<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_24August 2023</name>
   <tag></tag>
   <elementGuidId>f27258cb-894c-44c0-8c94-b47aab808840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[36]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b93a39bc-e22c-4f37-87bd-8e694984340f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiPickersDay-root MuiPickersDay-dayWithMargin css-1bxhmj7</value>
      <webElementGuid>e274307b-8a38-429b-a6d6-9e2130061047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e202ca6e-e3f7-4939-9ee5-84d75fa9f5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b27cb39a-b468-4a02-98a4-b978c0814b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>bb4b8c4d-c646-488b-a444-d7d99ca4584a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-timestamp</name>
      <type>Main</type>
      <value>1692828000000</value>
      <webElementGuid>40b4e56d-7d0a-4fab-9b92-af455bbfe583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>812fdd7b-2d1c-4ca8-b4b8-ff5a875f0c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b223901-3cc8-4632-bce3-4894e03e2b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>1d02fc89-8a79-4437-b3f7-f500f2c1f80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPickersPopper-root css-1mtsuo7 MuiPopper-root&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPickersPopper-paper css-1bk1bgq&quot;]/div[@class=&quot;MuiPickersLayout-root css-192l38i&quot;]/div[@class=&quot;MuiPickersLayout-contentWrapper css-lz05jy&quot;]/div[@class=&quot;MuiDateCalendar-root css-1080di7&quot;]/div[@class=&quot;MuiPickersFadeTransitionGroup-root MuiDateCalendar-viewTransitionContainer css-1h73gvd&quot;]/div[1]/div[1]/div[@class=&quot;MuiPickersSlideTransition-root MuiDayCalendar-slideTransition css-2ldko6&quot;]/div[@class=&quot;MuiDayCalendar-monthContainer css-i6bazn&quot;]/div[@class=&quot;MuiDayCalendar-weekContainer css-mvmu1r&quot;]/button[@class=&quot;MuiButtonBase-root MuiPickersDay-root MuiPickersDay-dayWithMargin css-1bxhmj7&quot;]</value>
      <webElementGuid>8d633ef3-4247-4f51-8fbb-45ee966bde7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[36]</value>
      <webElementGuid>46051c5e-bd5f-4e63-b174-0d9e392a2688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::button[24]</value>
      <webElementGuid>29cb4125-b485-45cb-8eef-7f525d25441e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::button[24]</value>
      <webElementGuid>cf679d66-74f0-4750-a3fa-980ff3dc2441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24']/parent::*</value>
      <webElementGuid>ee56eb20-5ac9-43a4-9b1e-d89cb8dba8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[5]</value>
      <webElementGuid>36f8f030-a2e1-4393-9cac-755acf36de88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '24' or . = '24')]</value>
      <webElementGuid>a31f8c72-907a-42d8-8f71-99798579a797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
