<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Auditoi</name>
   <tag></tag>
   <elementGuidId>234cc548-4ff5-4238-97d7-d8e783533349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[1]/div[2]/div[1]/div[@class=&quot;MuiBox-root css-bawa6j&quot;]/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[@class=&quot;MuiList-root css-1mfs4nj&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItemButton-root MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-gutters css-1qubh4e&quot;]/a[@class=&quot;active&quot;]/span[@class=&quot;label&quot;][count(. | //*[(text() = 'Auditoři' or . = 'Auditoři')]) = count(//*[(text() = 'Auditoři' or . = 'Auditoři')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div/div[1]/div/div/div[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e3e455e-16e2-4191-96a9-18f2cc67e9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7efc0b13-6067-41c3-b5ee-67058bb222c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Auditoři</value>
      <webElementGuid>2e08b60c-49b5-4015-a78a-f6a62658c4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[1]/div[2]/div[1]/div[@class=&quot;MuiBox-root css-bawa6j&quot;]/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[@class=&quot;MuiList-root css-1mfs4nj&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItemButton-root MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-gutters css-1qubh4e&quot;]/a[@class=&quot;active&quot;]/span[@class=&quot;label&quot;]</value>
      <webElementGuid>5fd40680-2001-44a7-98f6-63d083299a09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/a/span[2]</value>
      <webElementGuid>4b8835de-d6fa-4b21-b980-fed646bcb13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporty'])[1]/following::span[14]</value>
      <webElementGuid>b95f73c6-f687-48d7-b969-51f51d57ffac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nastavení'])[1]/following::span[14]</value>
      <webElementGuid>89e53333-2c1f-4a23-894a-fc2a7542190d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výrobní místa'])[1]/preceding::span[3]</value>
      <webElementGuid>6b1a01ba-444a-4faf-8766-17a10427d0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalogy otázek'])[1]/preceding::span[6]</value>
      <webElementGuid>bf75c2d2-fdbe-4c5b-848a-242db5fe6d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Auditoři']/parent::*</value>
      <webElementGuid>9ca14c02-0695-4c94-9bed-af793365c101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>a48532b1-13f8-49d7-a7d7-e7da43512db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Auditoři' or . = 'Auditoři')]</value>
      <webElementGuid>5a81d2ed-4801-4c87-b7c4-6d1a76ca3b97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
