<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Mlad Boleslav - Vroba voz</name>
   <tag></tag>
   <elementGuidId>029f83b8-89fa-4177-acce-a84178fdf8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='be7d65a5-8317-4fe7-b77a-106a7781618c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#be7d65a5-8317-4fe7-b77a-106a7781618c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0fd06506-17c7-431b-8c74-5c2c98135df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-1kyucs5</value>
      <webElementGuid>2bd5c0b3-8bb8-4d38-b370-08fa3e2a2531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a4f611b6-1050-44e6-94cb-35816614443a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a946d013-1500-4aa1-a13b-4bf77a428d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>be7d65a5-8317-4fe7-b77a-106a7781618c</value>
      <webElementGuid>f88cdf51-2bbd-438d-9217-fadcda87c6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a0957ea6-3a37-48b7-85fe-d229e49a5487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>be7d65a5-8317-4fe7-b77a-106a7781618c</value>
      <webElementGuid>7170a0d3-5c18-4dda-b3ac-f80194cd11c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mladá Boleslav - Výroba vozů</value>
      <webElementGuid>825508d0-601a-494e-9009-695b8673be92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be7d65a5-8317-4fe7-b77a-106a7781618c&quot;)</value>
      <webElementGuid>b2638812-88ba-40da-8233-dd9302ff1168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='be7d65a5-8317-4fe7-b77a-106a7781618c']</value>
      <webElementGuid>04dba89c-5c10-4746-b87c-a772b5a5beb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li[5]</value>
      <webElementGuid>ebf422af-9169-45c4-b730-957244b3cf3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[2]/following::li[1]</value>
      <webElementGuid>50418a90-435c-4091-b4a9-1020ab15f5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test1'])[1]/following::li[2]</value>
      <webElementGuid>787a18be-df26-4f7d-80d3-1e471d099b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Damiq Test (copy)'])[1]/preceding::li[1]</value>
      <webElementGuid>ee527f1c-e6ec-435f-b2cd-3f6b23455961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výrobní Místo B'])[1]/preceding::li[2]</value>
      <webElementGuid>8194ada1-71ec-43b2-a479-42acd15ba21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mladá Boleslav - Výroba vozů']/parent::*</value>
      <webElementGuid>c9effcc3-c326-4e6b-ad9d-a34a4e2c62b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]</value>
      <webElementGuid>a4a6957e-7d31-4a55-9f4e-3fee7bef5843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'be7d65a5-8317-4fe7-b77a-106a7781618c' and (text() = 'Mladá Boleslav - Výroba vozů' or . = 'Mladá Boleslav - Výroba vozů')]</value>
      <webElementGuid>fe51229f-c62c-4e6e-ad7c-5723c2fd609e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
