<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vrobn msta</name>
   <tag></tag>
   <elementGuidId>3e9e683b-c074-481b-984f-50094ad06a02</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div/div[2]/div/div/div/div[2]/div[1]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'paudit-select' and (text() = '​' or . = '​')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paudit-select</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66fbc609-90f3-4a3e-bd26-f4a98a81eee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12b2c844-abee-4c69-acec-f9e31a624e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>090e14ad-e64f-4d25-a354-cde39effb6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>909ce314-d123-4816-b0a1-a33774e25e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>1bde8afb-9306-4950-a9c1-e0c6f510f537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>paudit-select-label paudit-select</value>
      <webElementGuid>c77096d5-df5c-4e01-bea6-e01c1996d136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paudit-select</value>
      <webElementGuid>4e1fa8c7-41e9-49e8-91c6-7b1df65cbc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-select MuiSelect-filled MuiInputBase-input MuiFilledInput-input css-lc5al6</value>
      <webElementGuid>0cc29161-493a-434e-92aa-c6952638a7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>ac324747-4988-4f64-959a-6b173aea43cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PAudit&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[@class=&quot;MuiContainer-root undefined undefined css-runt2f&quot;]/div[@class=&quot;items-in-row&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-fullWidth css-18cb7ou&quot;]/div[@class=&quot;MuiInputBase-root MuiFilledInput-root MuiFilledInput-underline MuiInputBase-colorPrimary Mui-focused MuiInputBase-formControl  css-k2ndak&quot;]/div[@id=&quot;paudit-select&quot;]</value>
      <webElementGuid>3c993c8b-70cc-41d1-a0cf-c8d7e580b7a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='paudit-select']</value>
      <webElementGuid>4e9a6e00-7073-42e1-b475-8ba58dedf1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PAudit']/div/div/div[2]/div/div/div</value>
      <webElementGuid>314c7dae-89cc-4469-ab04-0cb262cb4b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výrobní místo'])[1]/following::div[2]</value>
      <webElementGuid>a15ee1c5-e63c-4018-9f3f-8aa6144aa87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::div[4]</value>
      <webElementGuid>d497f37b-560e-4c43-abea-e03ad4073714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výrobní oblast'])[1]/preceding::div[1]</value>
      <webElementGuid>56788c19-f72a-4bda-a11b-d1d43eede8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>ddae9b22-dafc-4f9f-bd74-9d74392eca3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'paudit-select' and (text() = '​' or . = '​')]</value>
      <webElementGuid>9208a7c2-07a9-470e-bf02-e8ff39705108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
