<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <elementGuidId>d2a34357-4aff-45b8-bf3e-1ee9af0788ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>321f7b98-6a39-482c-98ca-a403e66d8c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>e9e36727-5748-4d6f-9588-5a85533c2ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-login textbox </value>
      <webElementGuid>f50b638a-3e95-4074-9b7c-38608aedf59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(function(evt){var c=evt.charCode;return(c===0||c>=48&amp;&amp;c&lt;=57||c>=65&amp;&amp;c&lt;=90||c>=97&amp;&amp;c&lt;=122)})(event)</value>
      <webElementGuid>2316703d-097b-45ef-a119-cf060579a499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07737904-abca-4ba2-9ba9-a90d977c295f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name / Personal number</value>
      <webElementGuid>582446b7-eb37-4173-8451-16caa591d978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainform&quot;)/input[@class=&quot;input-login textbox&quot;]</value>
      <webElementGuid>03f2d137-b9bf-4e1c-afcd-c36409e788b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userName']</value>
      <webElementGuid>bc2a14a8-6347-4566-b246-105e3e667959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainform']/input[4]</value>
      <webElementGuid>4872339d-3e1a-418f-9430-75c130fcf59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>b5d7e4fd-4b89-4a04-bb68-93c1b4d0dd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'userName' and @type = 'text' and @placeholder = 'User name / Personal number']</value>
      <webElementGuid>812b5578-b078-42bc-9fa4-ecb43908a2d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
