<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FiltrVrobnMsto</name>
   <tag></tag>
   <elementGuidId>b01f59ff-8aa0-44c7-97de-85834e94b243</elementGuidId>
   <imagePath>Screenshots/Targets/Plánování/FiltrVýrobníMísto.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Plánování/FiltrVýrobníMísto.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='paudit-select'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;paudit&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[@class=&quot;MuiContainer-root undefined undefined css-runt2f&quot;]/div[@class=&quot;items-in-row&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-fullWidth css-18cb7ou&quot;]/div[@class=&quot;MuiInputBase-root MuiFilledInput-root MuiFilledInput-underline MuiInputBase-colorPrimary Mui-focused MuiInputBase-formControl  css-k2ndak&quot;]/div[@id=&quot;paudit-select&quot;][count(. | //*[@id = 'paudit-select' and @class = 'MuiSelect-select MuiSelect-filled MuiInputBase-input MuiFilledInput-input css-lc5al6' and (text() = '​' or . = '​')]) = count(//*[@id = 'paudit-select' and @class = 'MuiSelect-select MuiSelect-filled MuiInputBase-input MuiFilledInput-input css-lc5al6' and (text() = '​' or . = '​')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > label:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9f6e619-562c-4f77-9247-a6cedb457637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0166a179-d549-449f-b6a8-c636f2788b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>235e7af9-d572-4fe8-8d9f-5741c273cc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a934d2f1-1209-4138-9c11-c3735d16c1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>94b6df9a-c57b-408f-a348-4a15cf62a13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>paudit-select-label paudit-select</value>
      <webElementGuid>70aa3c92-8a3c-43e2-8b54-5cac42e2d0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paudit-select</value>
      <webElementGuid>860dbe83-b5c0-44b8-a1b8-8713d59ffc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-select MuiSelect-filled MuiInputBase-input MuiFilledInput-input css-lc5al6</value>
      <webElementGuid>8a2d59e7-f582-485c-9b77-08250979720b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>7dfc3209-22e3-42f9-946a-99ec223ddc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paudit&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-12i9c2v&quot;]/div[@class=&quot;MuiContainer-root undefined undefined css-runt2f&quot;]/div[@class=&quot;items-in-row&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-fullWidth css-18cb7ou&quot;]/div[@class=&quot;MuiInputBase-root MuiFilledInput-root MuiFilledInput-underline MuiInputBase-colorPrimary Mui-focused MuiInputBase-formControl  css-k2ndak&quot;]/div[@id=&quot;paudit-select&quot;]</value>
      <webElementGuid>d3e35248-8a1a-4019-ac44-09d061d8a5a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='paudit-select'])[2]</value>
      <webElementGuid>3c42ca62-d21b-4dac-b0d3-2ae90b7c4010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paudit']/div/div/div[4]/div/div/div</value>
      <webElementGuid>5fcd8ecf-e59e-491e-b5f8-1413e0177817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výrobní místo'])[1]/following::div[2]</value>
      <webElementGuid>f561ed0c-a2a3-4bf0-b172-b135f03f5111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[4]</value>
      <webElementGuid>211a483a-0c9e-4035-b50f-d6e3fc95ba72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výrobní oblast'])[1]/preceding::div[1]</value>
      <webElementGuid>15a92a28-71b3-49c3-b7da-e8113a5d705c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>cff6738b-8a9b-4db5-b1c4-15c1dec26928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'paudit-select' and (text() = '​' or . = '​')]</value>
      <webElementGuid>97c776de-d726-478e-bb67-961ac8bd2d23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
