<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name</name>
   <tag></tag>
   <elementGuidId>b685b5d2-cea6-4cbb-90e2-3f7df66cd1b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-61</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mui-61&quot;)[count(. | //*[@type = 'text' and @id = 'mui-61']) = count(//*[@type = 'text' and @id = 'mui-61'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-31']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ab87d0f-e1c4-45b0-9286-7f13acde5726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47f98b82-70a5-47d1-a05f-9d7799fae36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b6da0f1-66e2-45fa-9552-d04da1adf2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input css-zaqa72</value>
      <webElementGuid>38944a41-4ab1-46ec-9549-d835c1c92523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-61</value>
      <webElementGuid>c319f26a-0c78-49e5-9dfc-d9759bd4b904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-61&quot;)</value>
      <webElementGuid>64e1229e-5eae-408f-b7d1-ae9c38f80054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-61']</value>
      <webElementGuid>8bb2dc9e-990e-4357-8e70-c8e4d2524c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paudit']/div/div/div[2]/div/div/input</value>
      <webElementGuid>9583e644-3a45-4783-8882-6e38fd13e866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>58edc877-8178-4c85-9dd3-d375e81869d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mui-61']</value>
      <webElementGuid>9ae5df4b-fc48-4f9f-b9d3-1ac4273cd069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
