<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_newShortName_mui-42</name>
   <tag></tag>
   <elementGuidId>991c102b-c900-4f06-8e5f-6ef2a7138798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[3]/div[1]/div[1]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mui-42&quot;)[count(. | //*[@id = 'mui-42']) = count(//*[@id = 'mui-42'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-42</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ed973cb-119a-4e51-a27d-f634dfb13b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af81b95a-36c2-430f-9746-a9a7fef3bb0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae1c9898-1c28-42e1-8b8a-81817065a3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input css-zaqa72</value>
      <webElementGuid>b9e58778-26e2-4cba-8ffe-433bbef4c54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-42</value>
      <webElementGuid>c83ccb55-80bb-4c1a-9a1f-b82ed96c40dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-42&quot;)</value>
      <webElementGuid>be08cf03-2400-4b7a-8ca3-0ea726084fb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-42']</value>
      <webElementGuid>2d35cecf-0230-45eb-b4fa-b86434733874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5b32bef5-a38e-4047-9685-0696041d6018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mui-42']</value>
      <webElementGuid>88087146-f72d-4eec-b249-6d2db24b74e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
