<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Vrobn mstoB</name>
   <tag></tag>
   <elementGuidId>dbc2a2e1-0582-4fdc-be04-00f6a52e8257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0796cd47-57cc-40bb-b4cb-33311363dd9b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='0796cd47-57cc-40bb-b4cb-33311363dd9b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e005dcd1-c7d0-4887-9921-94a8e1f22445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-1kyucs5</value>
      <webElementGuid>2d144e05-4aab-4bc8-8445-1f5df220c84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a6de7291-4ccb-48a1-bc11-e7a46a0db04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>74beac04-9976-41a8-bc20-2d8b0c9be81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0796cd47-57cc-40bb-b4cb-33311363dd9b</value>
      <webElementGuid>642b26d8-096e-4322-a7f7-b4892aa492d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df580c50-ca74-4fc9-9192-6cdd001a58aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>0796cd47-57cc-40bb-b4cb-33311363dd9b</value>
      <webElementGuid>f6abb409-4c9a-4ce5-9ab5-59a3f75e0cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Výrobní Místo B</value>
      <webElementGuid>111e1fde-d7c7-43dd-be0e-b5d63a5bdeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0796cd47-57cc-40bb-b4cb-33311363dd9b&quot;)</value>
      <webElementGuid>1fdb321c-9843-4994-8008-20e057caad0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='0796cd47-57cc-40bb-b4cb-33311363dd9b']</value>
      <webElementGuid>ac3a1b79-354a-4b80-a4c8-7c0986039b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li[9]</value>
      <webElementGuid>e8f5aec9-0dcb-476a-843f-d479706f3a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výrobní místo B (copy)'])[2]/following::li[1]</value>
      <webElementGuid>2fa95141-5268-496b-a02c-4ea7a9b0ea9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Damiq Test (copy)'])[1]/following::li[2]</value>
      <webElementGuid>07dc882a-eee0-4e75-b6df-25fe242bb795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Škoda - ESD'])[1]/preceding::li[1]</value>
      <webElementGuid>8099275e-91ae-44a5-8fd3-fc9c6d56d981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[2]/preceding::li[2]</value>
      <webElementGuid>114c47b8-c59a-4bd2-aa0c-f06b1167c167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Výrobní Místo B']/parent::*</value>
      <webElementGuid>10550b53-b58e-4169-a10b-6a2fcb375b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]</value>
      <webElementGuid>0fbb7648-28bf-4c9e-a57a-781b629e0d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '0796cd47-57cc-40bb-b4cb-33311363dd9b' and (text() = 'Výrobní Místo B' or . = 'Výrobní Místo B')]</value>
      <webElementGuid>f2b5971b-192d-4d00-8b15-5cf51a6a5a19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
